import 'package:get/get.dart';

List iraq_cities = [
  "Baghdad".tr,
  "Basra".tr,
  "Nineveh".tr,
  "Erbil".tr,
  "Najaf".tr,
  "Maysan".tr,
  "Qadisiyah".tr,
  "Diyala".tr,
  "Anbar".tr,
  "Kirkuk".tr,
  "Karbala".tr,
  "Babylon".tr,
  "Sulaymaniyah".tr,
  "Dohuk".tr,
  "Salahaddin".tr,
  "Wasit".tr,
  "Nasiriyah".tr,
  "Halabja".tr,
];

List specialties = [
  'الطب العام',
  'طب الاظفال',
  'جراحة الاظفال',
  'طب الاسنان',
  'الباطنية',
  'جراحة قلبية و اوعية دموية',
  'طب قلبية و اوعية دموية',
  'الطب النفسي',
  'طب الكلى و مسالك البولية',
  'جراحة الكلى و مسالك البولية',
  'جراحة الدماغ',
  'طب النسائية والتواليد',
  'الجراحات التجميلية',
  'الامراض الجلدية',
  'طب الاورام',
  'طب الجهاز الهضمي',
  'طب العيون',
  'جراحة العمود الفقري',
  'الغدد والسكري',
  'طب الصدرية و التنفسية',
  'اذن و انف وحنجرة',
  'جراحة العظام والكسور',
  'علاج طبيعي',
  'جراحة المفاصل والروماتيزم',
  'سونار و اشعة',
  'الطب النووي',
];

List weekDays = [
  "saturday".tr,
  "sunday".tr,
  "monday".tr,
  "tuesday".tr,
  "wednesday".tr,
  "thursday".tr,
  "friday".tr,
];
